export const COPY = {
  auth: {
    signIn: 'Sign In',
    signUp: 'Create Account',
    signInTitle: 'Welcome back',
    signUpTitle: 'Get started',
    signInSubtitle: 'Sign in to continue',
    signUpSubtitle: 'Create an account to get started',
    continueWithApple: 'Continue with Apple',
    continueWithGoogle: 'Continue with Google',
    orContinueWithEmail: 'or continue with email',
    email: 'Email',
    password: 'Password',
    noAccount: "Don't have an account? ",
    hasAccount: 'Already have an account? ',
    verifyTitle: 'Verify your email',
    verificationCode: 'Verification code',
    verify: 'Verify',
    forgotPassword: 'Forgot Password?',
    errors: {
      generic: 'Something went wrong. Please try again.',
    },
  },
  profile: {
    followers: 'Followers',
    following: 'Following',
    follow: 'Follow',
    following_button: 'Following',
    noFollowers: 'No followers yet',
    noFollowing: 'Not following anyone yet',
    userNotFound: 'User not found',
  },
  errors: {
    generic: 'Something went wrong. Please try again.',
    network: 'Check your internet connection.',
  },
} as const;
