export const COPY = {
  auth: {
    signIn: 'Sign In',
    signUp: 'Create Account',
    signInTitle: 'Welcome back',
    signUpTitle: 'Get started',
    signInSubtitle: 'Sign in to continue',
    signUpSubtitle: 'Create an account to get started',
    continueWithApple: 'Continue with Apple',
    continueWithGoogle: 'Continue with Google',
    orContinueWithEmail: 'or continue with email',
    email: 'Email',
    password: 'Password',
    noAccount: "Don't have an account? ",
    hasAccount: 'Already have an account? ',
    verifyTitle: 'Verify your email',
    verificationCode: 'Verification code',
    verify: 'Verify',
    forgotPassword: 'Forgot Password?',
    errors: {
      generic: 'Something went wrong. Please try again.',
    },
  },
  profile: {
    followers: 'Followers',
    following: 'Following',
    mealsCooked: 'Meals Cooked',
    follow: 'Follow',
    following_button: 'Following',
    noFollowers: 'No followers yet',
    noFollowing: 'Not following anyone yet',
    userNotFound: 'User not found',
  },
  cookbooks: {
    title: 'Cookbooks',
    newCookbook: 'New Cookbook',
    createCookbook: 'Create Cookbook',
    creating: 'Creating...',
    name: 'Name',
    namePlaceholder: 'My Recipes',
    description: 'Description',
    descriptionPlaceholder: 'A collection of my favorite dishes',
    optional: 'optional',
    recipeCount: (count: number) => (count === 1 ? '1 recipe' : `${count} recipes`),
    emptyTitle: 'No Cookbooks Yet',
    emptySubtitle: 'Create your first cookbook to start organizing recipes',
  },
  errors: {
    generic: 'Something went wrong. Please try again.',
    network: 'Check your internet connection.',
  },
  extraction: {
    title: 'Import Recipe',
    subtitle: 'Paste a video link to extract the recipe',
    placeholder: 'Paste TikTok, Instagram, or YouTube link',
    submit: 'Extract Recipe',
    extracting: 'Extracting...',
    status: {
      pending: 'Queued',
      scraping: 'Analyzing video...',
      transcribing: 'Transcribing audio...',
      analyzing: 'Processing video frames...',
      complete: 'Recipe extracted!',
      failed: 'Extraction failed',
    },
    errors: {
      invalidUrl: 'Please enter a valid video URL',
      notSignedIn: 'Sign in to import recipes',
      extractionFailed: 'Could not extract recipe from this video',
    },
  },
} as const;
