export const COPY = {
  auth: {
    signIn: 'Sign In',
    signUp: 'Create Account',
    signInTitle: 'Welcome back',
    signUpTitle: 'Get started',
    signInSubtitle: 'Sign in to continue',
    signUpSubtitle: 'Create an account to get started',
    continueWithApple: 'Continue with Apple',
    continueWithGoogle: 'Continue with Google',
    orContinueWithEmail: 'or continue with email',
    email: 'Email',
    password: 'Password',
    noAccount: "Don't have an account? ",
    hasAccount: 'Already have an account? ',
    verifyTitle: 'Verify your email',
    verificationCode: 'Verification code',
    verify: 'Verify',
    forgotPassword: 'Forgot Password?',
    errors: {
      generic: 'Something went wrong. Please try again.',
    },
  },
  profile: {
    followers: 'Followers',
    following: 'Following',
    mealsCooked: 'Meals Cooked',
    follow: 'Follow',
    following_button: 'Following',
    noFollowers: 'No followers yet',
    noFollowing: 'Not following anyone yet',
    userNotFound: 'User not found',
  },
  cookbookDetail: {
    recentlyCooked: 'Recently Cooked',
    suggestedRecipe: 'Suggested Recipe',
    add: 'Add',
    yourRecipesPrefix: 'Your',
    yourRecipesBold: 'Recipes',
    cook: 'Cook',
    searchPlaceholder: 'Search recipes...',
    emptyTitle: 'No recipes yet',
    emptySubtitle: 'Tap + to add your first recipe',
    addRecipe: 'Add Recipe',
    notFound: 'Cookbook not found',
    minuteShort: 'min',
    recipeOptions: {
      viewRecipe: 'View Recipe',
      moveToCookbook: 'Move to Cookbook',
      deleteFromCookbook: 'Remove from Cookbook',
      cancel: 'Cancel',
      selectCookbook: 'Select Cookbook',
      moveSuccess: 'Recipe moved',
      deleteConfirm: 'Remove this recipe from the cookbook?',
    },
  },
  cookbooks: {
    title: 'Cookbooks',
    newCookbook: 'New Cookbook',
    createCookbook: 'Create Cookbook',
    creating: 'Creating...',
    name: 'Name',
    namePlaceholder: 'My Recipes',
    description: 'Description',
    descriptionPlaceholder: 'A collection of my favorite dishes',
    optional: 'optional',
    recipeCount: (count: number) => (count === 1 ? '1 recipe' : `${count} recipes`),
    emptyTitle: 'No Cookbooks Yet',
    emptySubtitle: 'Create your first cookbook to start organizing recipes',
  },
  errors: {
    generic: 'Something went wrong. Please try again.',
    network: 'Check your internet connection.',
  },
  extraction: {
    title: 'Import Recipe',
    subtitle: 'Paste a video URL from TikTok, Instagram, or YouTube',
    placeholder: 'https://youtube.com/watch?v=...',
    submit: 'Extract Recipe',
    extracting: 'Extracting recipe...',
    checking: 'Checking for existing recipe...',
    saving: 'Saving to your collection...',
    tryAgain: 'Try again',
    importAnother: 'Import Another',
    extractedRecipe: 'Extracted Recipe',
    extractedVia: 'Extracted via:',
    tier: 'tier',
    by: 'By',
    ingredients: 'Ingredients',
    instructions: 'Instructions',
    dietary: 'Dietary',
    equipment: 'Equipment',
    alreadyExists: 'Recipe already in database - added to your collection',
    rateThisRecipe: 'Rate this recipe:',
    communityAverage: (rating: number) => `Community average: ${rating.toFixed(1)} stars`,
    status: {
      idle: 'Ready',
      checking: 'Checking...',
      extracting: 'Extracting...',
      saving: 'Saving...',
      complete: 'Complete',
      error: 'Error',
    },
    meta: {
      servings: (n: number) => `${n} servings`,
      minutes: (n: number) => `${n} min`,
    },
    servings: {
      label: 'Servings',
      reset: 'Reset to original',
      was: (n: number) => `(was ${n})`,
    },
    cookbook: {
      selectCookbook: 'Add to Cookbook',
      selectPlaceholder: 'Select a cookbook...',
      createNew: '+ Create New Cookbook',
      required: 'Please select a cookbook',
      noCookbooks: 'No cookbooks yet',
    },
    errors: {
      invalidUrl: 'Please enter a valid video URL',
      notSignedIn: 'Sign in to import recipes',
      extractionFailed: 'Could not extract recipe from this video',
      noData: 'No recipe data received',
      noRecipe: 'No recipe found',
    },
    viewRecipe: 'View Recipe',
  },
  addModal: {
    main: {
      title: 'Add',
    },
    importUrl: {
      title: 'Import Recipe',
      urlLabel: 'Recipe URL',
      placeholder: 'Paste a video URL...',
      submit: 'Import',
      submitActive: 'Import Recipe',
      importing: 'Importing...',
    },
    addRecipe: {
      title: 'Add Recipe',
      urlLabel: 'Recipe URL',
      placeholder: 'Paste a recipe link...',
      hint: 'Share from TikTok, Instagram, YouTube, or any recipe website',
      submit: 'Add Recipe',
    },
    options: {
      importUrl: 'Import from URL',
      importUrlDesc: 'Save a recipe from a video or website',
      createRecipe: 'Create Recipe',
      createRecipeDesc: 'Write your own recipe from scratch',
      sharePost: 'Share a Cook',
      sharePostDesc: 'Share something you made',
    },
    createRecipe: {
      title: 'Create Recipe',
      name: 'Recipe Name',
      namePlaceholder: 'My Amazing Dish',
      description: 'Description',
      descriptionPlaceholder: 'A brief description of your recipe...',
      ingredients: 'Ingredients',
      ingredientsPlaceholder: 'Add ingredients one per line...',
      instructions: 'Instructions',
      instructionsPlaceholder: 'Add cooking steps...',
      submit: 'Create Recipe',
      creating: 'Creating...',
    },
    sharePost: {
      title: 'Share a Meal',
      selectRecipe: 'Select Recipe',
      searchPlaceholder: 'Search your recipes...',
      ratings: {
        ease: 'How easy was it?',
        taste: 'How tasty was it?',
        presentation: 'How did it look?',
      },
      notes: 'Notes',
      notesPlaceholder: 'Any thoughts on how it turned out?',
      submit: 'Share',
      sharing: 'Sharing...',
      noRecipes: 'No recipes yet',
      noRecipesDesc: 'Import or create a recipe first',
      selectRecipeFirst: 'Select a recipe to rate',
    },
    back: 'Back',
    cancel: 'Cancel',
  },
  pantry: {
    tabs: {
      mealPlan: 'Meal Plan',
      yourFood: 'Your Food',
      groceries: 'Groceries',
    },
    mealPlan: {
      emptyTitle: 'Plan Your Meals',
      emptySubtitle: 'Organize your weekly meals and stay on track',
      today: 'Today',
      mealTypes: {
        breakfast: 'Breakfast',
        lunch: 'Lunch',
        dinner: 'Dinner',
        snack: 'Snacks',
      },
      addRecipe: 'Add Recipe',
      searchPlaceholder: 'Search saved recipes...',
      noSavedRecipes: 'No saved recipes yet',
      noResults: 'No recipes found',
      remove: 'Remove',
    },
    yourFood: {
      emptyTitle: 'Track Your Pantry',
      emptySubtitle: 'Add ingredients you have on hand',
    },
    groceries: {
      emptyTitle: 'Shopping List',
      emptySubtitle: 'Add items you need to buy',
    },
  },
  posts: {
    ratings: {
      ease: 'Ease',
      taste: 'Taste',
      presentation: 'Presentation',
    },
    emptyTitle: 'No Posts Yet',
    emptySubtitle: 'Share your first recipe to see it here',
  },
  shareIntent: {
    title: 'Save Recipe',
    selectCookbook: 'Choose a cookbook',
    import: 'Import',
    cancel: 'Cancel',
    urlPreview: 'Recipe from',
    progress: {
      queued: 'Queued...',
      checking: 'Checking...',
      extracting: 'Extracting...',
      saving: 'Saving...',
    },
    success: {
      title: 'Recipe saved',
      viewRecipe: 'View',
    },
    error: {
      title: 'Import failed',
      retry: 'Try Again',
    },
    clipboard: {
      prompt: (domain: string) => `Import recipe from ${domain}?`,
      import: 'Import',
      dismiss: 'Dismiss',
    },
  },
  recipeDetail: {
    title: 'Recipe',
    notFound: 'Recipe not found',
    rateThisRecipe: 'Rate this recipe:',
    communityAverage: (rating: number) => `Community average: ${rating.toFixed(1)} stars`,
    by: 'By',
    ingredients: 'Ingredients',
    instructions: 'Instructions',
    dietary: 'Dietary',
    equipment: 'Equipment',
    extractedVia: 'Extracted via:',
    tier: 'tier',
    minutes: (n: number) => `${n} min`,
    servings: {
      label: 'Servings',
      reset: 'Reset to original',
      was: (n: number) => `(was ${n})`,
    },
    nutrition: {
      title: 'Nutrition',
      calories: 'Calories',
      protein: 'Protein',
      carbs: 'Carbs',
      fat: 'Fat',
      perServing: 'Per serving (estimated)',
    },
    yourReview: {
      title: 'Your Review',
      ease: 'Ease',
      taste: 'Taste',
      presentation: 'Presentation',
      notes: 'Notes',
      noNotes: 'No notes added',
      save: 'Save',
      saving: 'Saving...',
    },
  },
  socialFeed: {
    title: 'Feed',
    searchTitle: 'Search',
    searchPlaceholder: 'Search users...',
    suggestedUsers: 'Suggested for you',
    searchResults: 'Search results',
    noResults: 'No users found',
    tryDifferentSearch: 'Try a different search term',
    noSuggestions: 'No suggestions',
    searchToFind: 'Search to find people to follow',
    emptyFeedTitle: 'Your feed is empty',
    emptyFeedSubtitle: 'Follow people to see their posts here',
    findPeople: 'Find People',
    tabs: {
      feed: 'Feed',
      search: 'Search',
    },
  },
  discover: {
    title: 'Discover',
    subtitle: 'Swipe to find your next meal',
    tabs: {
      discover: 'Discover',
      feed: 'Feed',
      following: 'Following',
    },
  },
  comments: {
    title: 'Comments',
    placeholder: 'Add a comment...',
    post: 'Post',
    posting: 'Posting...',
    empty: 'No comments yet',
    beFirst: 'Be the first to comment',
    delete: 'Delete',
    deleteConfirm: 'Delete this comment?',
    errors: {
      empty: 'Comment cannot be empty',
      tooLong: 'Comment must be 500 characters or less',
      failed: 'Failed to post comment',
    },
  },
} as const;
